### ISSUE TITLE
ImportError: cannot import name 'LaneNet' from 'lanenet.model' (/home/wxd/anaconda3/lib/python3.7/site-packages/lanenet-0.1.0-py3.7.egg/lanenet/model/__init__.py)

### ISSUE THREAD

**Issue by weweus** [klintan/pytorch-lanenet#1]
Thx for your repo, but when I run the demo "python3 ./lanenet/train.py --dataset ./data/training_data_example", the error "ImportError: cannot import name 'LaneNet' from 'lanenet.model' (/home/wxd/anaconda3/lib/python3.7/site-packages/lanenet-0.1.0-py3.7.egg/lanenet/model/__init__.py)" occurs. How can I solve this problem?

**Comment by klintan** [comment]
Oh thanks for filing an issue. It should be fixed in the latest commit. Let me know if it still doesn't work.
