### ISSUE TITLE
ModuleNotFoundError: No module named 'skimage'

### ISSUE THREAD

**Issue by ayushmankumar7** [klintan/pytorch-lanenet#19]
![Screenshot from 2021-04-25 21-11-17](https://user-images.githubusercontent.com/41910134/115999817-e6fa9e00-a60a-11eb-84a2-d7f7531ef8b7.png)

**Comment by klintan** [comment]
You should be able to do `pip install -U scikit-image` 
I'll add it to the `requirements.txt` file if it's not there already.
