### ISSUE TITLE
how to compose image??

### ISSUE THREAD

**Issue by sabadijou** [klintan/pytorch-lanenet#26]
Hi 
you used the following code in test.py. there are three methods that I couldn't find them (compose_img, val_img_md5, lane_cluster_and_draw). where can I find these methods ???? 
        if step % 100 == 0:
           val_img_list.append(
              compose_img(image_data, out, binary_label, net_output["instance_seg_logits"], instance_label, 0))
              val_img_md5.write(input_data["img_name"][0] + "\n")
              lane_cluster_and_draw(image_data, net_output["binary_seg_pred"], net_output["instance_seg_logits"], input_data["o_size"], input_data["img_name"], json_path)

**Comment by shreyventure** [comment]
Hi @sabadijou ! This repository has taken the reference from [lanenet-danet-pytorch](https://github.com/leonfrank/lanenet-danet-pytorch) repository. So you might find these functions there.
For an example, here's [lane_cluster_and_draw](https://github.com/leonfrank/lanenet-danet-pytorch/blob/9236908b9d843eac79d7f470550c20243aa766b6/train_lanenet.py#L115).
Thanks.
