### ISSUE TITLE
about the LaneNet

### ISSUE THREAD

**Issue by monsterlyg** [klintan/pytorch-lanenet#4]
What do you mean the architecture of  "LaneNet: Real-Time Lane Detection Networks for Autonomous Driving" is the same as 1. The paper does not clearly indicate the parameters of each layer. Especially the Channel. I am not sure what they should be. Do you have any idea? And the 1 is 'Towards End-to-End Lane Detection: an Instance Segmentation Approach' ？

**Comment by eeyrw** [comment]
I agree with you. I do not think these two papers have similarity. The paper "LaneNet: Real-Time..." (LRT) use a very different way comparing with "Towards End-to-End..."(TEE) to distinguish different lanes. Furthermore, LRT do not apply end-to-end techniques to train network.

**Comment by klintan** [comment]
> I agree with you. I do not think these two papers have similarity. The paper "LaneNet: Real-Time..." (LRT) use a very different way comparing with "Towards End-to-End..."(TEE) to distinguish different lanes. Furthermore, LRT do not apply end-to-end techniques to train network.

Yes you are right, I was a bit to generous calling them similar at the time. I'll remove that reference, the implementation is for the "Towards E2E ...".

**Comment by klintan** [comment]
Removed the reference from the readme :)
