### ISSUE TITLE
Determining if loading a pretrained model was successful 

### ISSUE THREAD

**Issue by rahilmodi97** [klintan/pytorch-lanenet#9]
Hello,
My concern is while writing python lanenet/train.py -- dataset path to the folder --pretrained path to the pretrained model. Is there any way to determine if the pretrained model has loaded successfully or not as running it with or without the --pretrained argument it is not clear whether the model has loaded or not. Can you help me with this issue?

**Comment by klintan** [comment]
Hm that is good point. It's probably just a matter of adding a small logging / print statement if the models i successfully loaded when running the `train.py` file. Feel free to add a PR and i'll review it:)
